# More info on config here: https://golangci-lint.run/usage/configuration
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax # allow unless explicitely denied
        deny:
          - pkg: "reflect"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - prealloc
    - noctx
    - revive
    - govet
    - errcheck
    - ineffassign
    - goprintffuncname
    - typecheck
    - goconst
    - gosec
    - goimports
    - unused
    - staticcheck
    - gocyclo
    - wsl
    - gocritic
    - depguard

issues:
  new-from-rev: ""
  exclude-use-default: false
  exclude:
    - should have a package comment, unless it's in another file for this package
    - don't use an underscore in package name
    - should check returned error before deferring
    - "exported (type|method|function|const) (.+) should have comment"
    # _ instead of err checks
    - G104
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    # выключено из-за all_caps констант модуля sense hat (c)
    - "don't use ALL_CAPS in Go names; use CamelCase" 
    - "don't use underscores in Go names; const"
    - unused-parameter
  exclude-dirs:
    - bin
    - test
  exclude-rules:
    - path: ".*\\.*_test\\.go$"
      linters:
        - dupl
        - wsl
        - gosec
        - prealloc
        - gocognit
        - gocyclo
        - errcheck
        - noctx
